name: GoQuadro blog
description: "The GoQuadro Blog"
markdown: redcarpet
pygments: true
permalink: /:title/
timezone: Europe/Rome
baseurl: http://blog.goquadro.com
include: ['_pages']
exclude:
- README.md
- CNAME
