name: GoQuadro blog
description: "The GoQuadro Blog"
markdown: redcarpet
pygments: true
relative_permalinks: false
timezone: Europe/Rome
baseurl: http://blog.goquadro.com
include: ['_pages']
exclude:
- README.md
- CNAME
